spring.application.name=ECommerce

spring.datasource.url = jdbc:h2:mem:test
spring.h2.console.enabled=true
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.formate_sql = true

project.image = images/
#debug = true

